//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("MvvmScarletToolkit")]
[assembly: AssemblyVersion("2.0.7.0")]
[assembly: AssemblyFileVersion("2.0.7.0")]
[assembly: AssemblyInformationalVersion("2.0.7.0")]
[assembly: AssemblyCopyright("© 2019 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("Compiled on:", "[UTC]22.06.2019 18:18:55")]
