//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("MvvmScarletToolkit")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("2.0.0.0")]
[assembly: AssemblyCopyright("© 2018 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("Compiled on:", "[UTC]04.12.2018 19:53:47")]
