//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("MvvmScarletToolkit")]
[assembly: AssemblyCopyright("© 2023 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]11.12.2023 18:57:07")]
[assembly: AssemblyMetadata("PublicRelease", "False")]
[assembly: AssemblyMetadata("Branch", "master")]
[assembly: AssemblyMetadata("Commit", "4fec16fade51403d923274dc22def24b4b99c5d0")]
[assembly: AssemblyMetadata("Version", "3.0.93")]
