//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("MvvmScarletToolkit")]
[assembly: AssemblyCopyright("© 2022 Insire")]
[assembly: AssemblyTrademark("")]
// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
